name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: publish-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify release version matches tag
        id: verify
        shell: bash
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          TAG="${GITHUB_REF##*/}"
          TAG_NO_V=${TAG#v}
          echo "Version: $VERSION | Tag: $TAG"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "Project version is a SNAPSHOT; refusing to release." >&2
            exit 1
          fi
          if [[ "$VERSION" != "$TAG_NO_V" ]]; then
            echo "Project version ($VERSION) does not match tag ($TAG_NO_V)." >&2
            exit 1
          fi

      - name: Configure credentials for Gradle
        shell: bash
        run: |
          mkdir -p ~/.gradle
          cat >> ~/.gradle/gradle.properties <<'EOF'
          sonatypeUsername=${{ secrets.SONATYPE_USERNAME }}
          sonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
          signing.key=${{ secrets.SIGNING_KEY }}
          signing.password=${{ secrets.SIGNING_PASSWORD }}
          EOF

      - name: Build and publish (close & release)
        shell: bash
        run: |
          ./gradlew --no-daemon --stacktrace clean build publishToSonatype closeAndReleaseSonatypeStagingRepository
